PR - The first point of homework
zsvs/ITEA_Stepanets pull request #4
Opened 2021-05-12 21:14 UTC by zsvs

Added dockerfile for building container that work with "git clone".
It'll take git-URL which passing into environment variable for cloning git repos to local host.
By default, environment variable = "https://github.com/Dgadavin/itea-base-course.git"

2021-05-13 06:40 UTC, Dgadavin requested changes

2021-05-13 06:40 UTC, Dgadavin commented on Docker/Dockerfile.git
> +RUN apt-get install --no-install-recommends --no-install-suggests -y git
Обьедините два рана в один. По факту команда то одна и та же.

2021-05-13 06:41 UTC, Dgadavin commented
Пока не мерджте. Добавьте еще задание с nginx

2021-05-16 15:59 UTC, zsvs commented
Добавил файлы для nginx

2021-05-17 12:19 UTC, Dgadavin approved these changes

2021-05-17 12:26 UTC, merged